title:  Ankit Kataria
tagline: Full Stack Web Developer 

# Authors documented under _data

# Change to true for Disqus comments
# disqus:
#   comments: false
#   disqus_shortname: 'https-lenpaul-github-io-lagrange'

# google-ID: 'UA-80213386-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Resume', path: 'menu', url: 'Resume/resumerevamp.pdf'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/ankitkataria'}
- {icon: 'twitter', link: 'https://twitter.com/ankitkataria28'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/ankitkataria28/'}
- {icon: 'envelope', link: 'mailto:me@ankitkataria.co'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
